language: java

services:
 - docker

install: true

os: linux
dist: trusty
jdk: openjdk8

before_script: cd backend
script:
 - ./gradlew build && ./gradlew test && ./gradlew bootJar

after_success:
  - docker build -t demobackend .
  - docker tag demobackend andraspatka/demobackend:latest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push andraspatka/demobackend